# Generated by Django 5.1.7 on 2025-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('ki', models.IntegerField()),
                ('max_ki', models.IntegerField()),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('affiliation', models.CharField(max_length=100)),
                ('origin_planet', models.CharField(max_length=100)),
            ],
        ),
    ]
