# Generated by Django 5.1.7 on 2025-04-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ki',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_ki',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
