# Generated by Django 5.1.7 on 2025-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_planets_alter_character_origin_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='origin_planet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
